version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: kek
      POSTGRES_PASSWORD: kek
      POSTGRES_DB: grooming_db
    ports:
      - "5432:5432"