version: "3.9"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: "grooming_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"